# Generated by Django 5.2.5 on 2026-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccount", "0002_pendinguser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "otp", "is_used"],
                        name="useraccount_email_17890f_idx",
                    )
                ],
            },
        ),
    ]
