# Generated by Django 5.2.5 on 2026-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.CharField(
                blank=True,
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("health", "Health"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
