# Generated by Django 5.2.5 on 2026-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_task_project_delete_project"),
        ("useraccount", "0003_passwordreset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("overdue", "Task Overdue"),
                    ("task_created", "Task Created"),
                    ("task_updated", "Task Updated"),
                    ("task_deleted", "Task Deleted"),
                    ("task_completed", "Task Completed"),
                    ("task_uncompleted", "Task Uncompleted"),
                    ("task_important", "Task Marked Important"),
                    ("task_unimportant", "Task Unmarked Important"),
                    ("project_assigned", "Project Assigned"),
                    ("project_changed", "Project Changed"),
                    ("due_soon", "Due Soon"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read", "-created_at"],
                name="main_app_no_user_id_abef09_idx",
            ),
        ),
    ]
